### ISSUE TITLE
spawn_local doesn't work inside winit loop

### ISSUE THREAD

**Issue by madmaxio** [dabreegster/minimal_websys_winit_glow_demo#1]
Hi, i'm trying to do same thing but with wgpu backend, but when I do spawn_local inside winit loop, it just doesn't start future. Any ideas why it is happening?

**Comment by dabreegster** [comment]
Sorry, I don't know. I lost context on how all of this works, honestly. If you ask around, I'd be surprised if you don't find someone who's figured out how to get wasm + winit + wgpu + starting an async call all playing together.

The [spawn_local docs](https://rustwasm.github.io/wasm-bindgen/api/wasm_bindgen_futures/fn.spawn_local.html) say it tries to run the future on the current thread, so in the browser, that sounds like a problem... I would expect `start_http_call` to just block in that case, rather than silently do nothing.

**Comment by madmaxio** [comment]
I found a solution with web worker, and it works for making async operations, if you are interested.
However without spawning futures in wgpu thread there it really looks not good. Created issue here https://github.com/gfx-rs/wgpu/issues/2306.

**Comment by dabreegster** [comment]
Extremely interested in example code! The last time I looked at web workers from Rust, either there weren't clear docs of how to use them, or the browser support was really inconsistent.

**Comment by madmaxio** [comment]
Thx to wgpu guys, this is now fixed by run_winit function from here:

https://github.com/BVE-Reborn/rend3/blob/trunk/rend3-framework/src/lib.rs#L133-L170

So worker is not needed now. Still I will post worker code later as you said one might find it usefull (let us not never underestimate threading).

**Comment by madmaxio** [comment]
Here is the code for worker creation, notice that worker code require separate js file with code for it, here it lives in a blob, but it can be just a file on the server (worker code is not wasm module code you will use in it, it is a separate file):


```
#[cfg(target_arch = "wasm32")]
fn create_worker(tx: UnboundedSender<Option<String>>) -> (Worker, Closure<dyn FnMut(MessageEvent)>) {    
    let host = web_sys::window().expect("Failed to get window").location().origin().expect("Failed to get origin");
    let js_url = "rust-crate-for-worker.js";
    let wasm_url = "rust-crate-for-worker_bg.wasm";

    let array = Array::new();
    array.push(
        &format!(
            r#"                
            importScripts("{0}{1}");
           
            const {{process_message_sent_to_worker}} = wasm_bindgen;

            async function run_wasm() {{
                await wasm_bindgen("{0}{2}");                                              
                
                self.onmessage = async event => {{
                    console.log(event);
                    let res = await process_message_sent_to_worker();
                    self.postMessage(res);
                }};                
            }}
            
            run_wasm();
            "#, host, js_url, wasm_url
        )
        .into(),
    );

    let blob = Blob::new_with_str_sequence_and_options(
        &array,
        BlobPropertyBag::new().type_("application/javascript"),
    )
    .unwrap();
    let url = Url::create_object_url_with_blob(&blob).unwrap();
    let worker = Worker::new(&url).expect("Failed to create worker");

    let mut persistent_callback_handle = get_on_msg_callback(tx);

    worker.set_onmessage(Some(persistent_callback_handle.as_ref().unchecked_ref()));        

    (worker, persistent_callback_handle)
}

#[cfg(target_arch = "wasm32")]
fn get_on_msg_callback(tx: UnboundedSender<Option<String>>) -> Closure<dyn FnMut(MessageEvent)> {
    let callback = Closure::wrap(Box::new(move |event: MessageEvent| {          
        let _ = tx.send(event.data().as_string());                
    }) as Box<dyn FnMut(_)>);

    callback
}
```
